TRANSLATIONS = {'de': {'about': 'Info',
        'about_subtitle': 'Leistungsstarker KI-Zielassistent',
        'about_title': 'Über Bartledoo',
        'aim_key_1': 'Zieltaste 1:',
        'aim_key_2': 'Zieltaste 2:',
        'aim_key_3': 'Zieltaste 3:',
        'aim_part': 'Zielbereich:',
        'aim_speed_pid': 'Zielgeschwindigkeit (PID)',
        'auto_aim': 'Automatisches Zielen',
        'auto_fire_key_1': 'Auto-Feuer-Taste 1:',
        'auto_fire_key_2': 'Auto-Feuer-Taste 2:',
        'auto_fire_target': 'Auto-Feuer-Ziel:',
        'body': 'Körper',
        'body_width_ratio': 'Körperbreitenanteil (%)',
        'both': 'Beides',
        'chinese': 'Chinesisch',
        'close': 'Schließen',
        'compute_mode': 'Rechenmodus',
        'config_load_failed': 'Konfiguration konnte nicht geladen werden',
        'config_loaded': 'Konfiguration geladen',
        'config_not_found': 'Konfigurationsdatei nicht gefunden, Standardwerte werden verwendet',
        'config_save_failed': 'Konfiguration konnte nicht gespeichert werden',
        'config_saved': 'Konfiguration gespeichert',
        'confirm_delete': 'Löschen bestätigen',
        'confirm_overwrite': 'Überschreiben bestätigen',
        'cpu': 'CPU',
        'create_preset': 'Preset erstellen',
        'delete_preset': 'Preset löschen',
        'detect_interval': 'Erkennungsintervall (ms)',
        'donate': 'Spenden',
        'donate_en': 'Donate',
        'enable_sound_alert': 'Soundwarnung aktivieren (beim Zielen auf Gegner)',
        'english': 'Englisch',
        'error_correction_i': 'Fehlerkorrektur (I)',
        'exit_and_save': 'Beenden und speichern',
        'export_preset': 'Preset exportieren',
        'fire_interval': 'Feuerintervall (s)',
        'fov_follow_mouse': 'FOV folgt der Maus',
        'fov_size': 'FOV-Größe',
        'function_options': 'Funktionsoptionen',
        'general_params': 'Allgemeine Parameter',
        'gpu_directml': 'DirectML (GPU)',
        'head': 'Kopf',
        'head_height_ratio': 'Kopfhöhenanteil (%)',
        'head_width_ratio': 'Kopfbreitenanteil (%)',
        'horizontal_x': 'Horizontal (X-Achse)',
        'i_am_human': 'Ich bin ein Mensch',
        'import_preset': 'Preset importieren',
        'join_discord': 'Discord beitreten',
        'keep_detecting': 'Erkennung beibehalten (auch ohne Zieltaste)',
        'key_listening': '[Taste wird aufgenommen...]',
        'keys_and_auto_fire': 'Tasten & Auto-Feuer',
        'language': 'Sprache',
        'load_preset': 'Preset laden',
        'min_confidence': 'Minimale Trefferwahrscheinlichkeit (%)',
        'model': 'Model:',
        'model_settings': 'Model Settings',
        'mouse_move_ddxoft': 'ddxoft',
        'mouse_move_method': 'Mausbewegungsmethode:',
        'no_selection': 'Keine Auswahl',
        'open_preset_folder': 'Preset-Ordner öffnen',
        'open_preset_manager': 'Preset-Manager öffnen',
        'parameter_name': 'Parametername',
        'preset_config': 'Preset-Konfiguration',
        'preset_error': 'Fehler',
        'preset_management_features': 'Preset-Verwaltungsfunktionen',
        'preset_manager': 'Preset-Manager',
        'preset_success': 'Erfolg',
        'preset_warning': 'Warnung',
        'program_control': 'Programmsteuerung',
        'reaction_speed_p': 'Reaktionsgeschwindigkeit (P)',
        'refresh_preset': 'Preset aktualisieren',
        'rename_preset': 'Preset umbenennen',
        'save_preset': 'Preset speichern',
        'scaling_close_button': 'Verstanden, Programm schließen',
        'scaling_current_setting': 'Aktuelle Windows-Skalierung: {}%',
        'scaling_explanation': 'Dieses Programm benötigt Windows-Skalierung auf 100%, um korrekt zu funktionieren. Andernfalls können sich die Zielpositionen verschieben.',
        'scaling_tutorial_content': '1. Klicken Sie mit der rechten Maustaste auf den Desktop und wählen Sie "Anzeigeeinstellungen"\n'
                                    '\n'
                                    '2. Oder drücken Sie Windows-Taste + I, öffnen Sie "Einstellungen" > "System" > "Anzeige"\n'
                                    '\n'
                                    '3. Suchen Sie den Bereich "Skalierung und Layout"\n'
                                    '\n'
                                    '4. Setzen Sie "Die Größe von Text, Apps und anderen Elementen ändern" auf 100%\n'
                                    '\n'
                                    '5. Wenn Sie mehrere Monitore verwenden, stellen Sie sicher, dass jeder auf 100% eingestellt ist\n'
                                    '\n'
                                    '6. Starten Sie den Computer neu oder melden Sie sich ab und wieder an, nachdem Sie die Änderung angewendet haben\n'
                                    '\n'
                                    '7. Starten Sie dieses Programm nach Abschluss neu, um genaues Zielen zu gewährleisten\n'
                                    '\n'
                                    'Tipps:\n'
                                    '- Wenn 100% zu klein erscheint, sollten Sie einen Monitor mit höherer Auflösung in Betracht ziehen\n'
                                    '- Möglicherweise müssen Sie die Fenstergrößen in anderen Apps danach anpassen\n'
                                    '- Die korrekte Skalierung hält das Zielen präzise und stabil',
        'scaling_tutorial_title': 'So beheben Sie das Problem:',
        'scaling_warning_main_title': 'Windows-Skalierungs-Konfigurationsproblem erkannt',
        'scaling_warning_title': 'Systemkonfigurationsproblem',
        'scope_delay': 'Visierverzögerung (s)',
        'show_boxes': 'Boxen anzeigen',
        'show_confidence': 'Erkennungswahrscheinlichkeit anzeigen',
        'show_fov': 'FOV anzeigen',
        'single_target_mode': 'Einzelzielmodus (fixiert den nächstgelegenen Gegner)',
        'sound_alert_system': 'Sound-Warnsystem',
        'sound_duration': 'Tondauer (ms)',
        'sound_frequency': 'Tonfrequenz (Hz)',
        'sound_interval': 'Tonintervall (ms)',
        'stability_suppression_d': 'Stabilitätsregelung (D)',
        'status_panel_compute_mode': 'Rechenmodus',
        'status_panel_current_model': 'Aktuelles Modell',
        'status_panel_off': 'Aus',
        'status_panel_on': 'An',
        'tab_aim_control': 'Zielsteuerung',
        'tab_auto_features': 'Automatische Funktionen',
        'tab_basic': 'Grundeinstellungen',
        'tab_display': 'Anzeigeoptionen',
        'tab_keys': 'Tastenbelegung',
        'tab_preset_management': 'Preset-Verwaltung',
        'tab_program_control': 'Programmsteuerung',
        'target_area_settings': 'Zielbereichseinstellungen',
        'toggle_auto_aim': 'Auto-Zielen umschalten',
        'toggle_key': 'Umschalttaste:',
        'version_info': 'Version 4.0 - Mit Liebe gemacht',
        'vertical_y': 'Vertikal (Y-Achse)',
        'view_github': 'GitHub ansehen',
        'window_title': 'Bartledoo_h0pZ_iis20160512@gmail.com'},
 'en': {'about': 'About',
        'about_subtitle': 'High-Performance AI Aim Assistant',
        'about_title': 'About Bartledoo',
        'aim_key_1': 'Aim Key 1:',
        'aim_key_2': 'Aim Key 2:',
        'aim_key_3': 'Aim Key 3:',
        'aim_part': 'Aim Part:',
        'aim_speed_pid': 'Aim Speed (PID)',
        'auto_aim': 'Auto Aim',
        'auto_fire_key_1': 'Auto Fire Key 1:',
        'auto_fire_key_2': 'Auto Fire Key 2:',
        'auto_fire_target': 'Auto Fire Target:',
        'body': 'Body',
        'body_width_ratio': 'Body Width Ratio (%)',
        'both': 'Both',
        'chinese': 'Chinese',
        'close': 'Close',
        'compute_mode': 'Compute Mode',
        'config_load_failed': 'Failed to load configuration',
        'config_loaded': 'Configuration Loaded',
        'config_not_found': 'Configuration file not found, using defaults',
        'config_save_failed': 'Failed to save configuration',
        'config_saved': 'Configuration Saved',
        'confirm_delete': 'Confirm Delete',
        'confirm_overwrite': 'Confirm Overwrite',
        'cpu': 'CPU',
        'create_preset': 'Create Preset',
        'delete_preset': 'Delete Preset',
        'detect_interval': 'Detection Interval (ms)',
        'donate': 'Donate',
        'donate_en': 'Donate',
        'enable_sound_alert': 'Enable Sound Alert (When Aiming at Enemy)',
        'english': 'English',
        'error_correction_i': 'Error Correction (I)',
        'exit_and_save': 'Exit & Save',
        'export_preset': 'Export Preset',
        'fire_interval': 'Fire Interval (s)',
        'fov_follow_mouse': 'FOV Follow Mouse',
        'fov_size': 'FOV Size',
        'function_options': 'Function Options',
        'general_params': 'General Parameters',
        'gpu_directml': 'DirectML (GPU)',
        'head': 'Head',
        'head_height_ratio': 'Head Height Ratio (%)',
        'head_width_ratio': 'Head Width Ratio (%)',
        'horizontal_x': 'Horizontal (X-axis)',
        'i_am_human': 'I am Human',
        'import_preset': 'Import Preset',
        'join_discord': 'Join Discord',
        'keep_detecting': 'Keep Detecting (Even Without Aim Key)',
        'key_listening': '[Press Key...]',
        'keys_and_auto_fire': 'Keys & Auto Fire',
        'language': 'Language',
        'load_preset': 'Load Preset',
        'min_confidence': 'Min Confidence (%)',
        'model': 'Model:',
        'model_settings': 'Model Settings',
        'mouse_move_ddxoft': 'ddxoft',
        'mouse_move_method': 'Mouse Move Method:',
        'no_selection': 'No Selection',
        'open_preset_folder': 'Open Preset Folder',
        'open_preset_manager': 'Open Preset Manager',
        'parameter_name': 'Parameter Name',
        'preset_config': 'Preset Configuration',
        'preset_error': 'Error',
        'preset_management_features': 'Preset Management Features',
        'preset_manager': 'Preset Manager',
        'preset_success': 'Success',
        'preset_warning': 'Warning',
        'program_control': 'Program Control',
        'reaction_speed_p': 'Reaction Speed (P)',
        'refresh_preset': 'Refresh Preset',
        'rename_preset': 'Rename Preset',
        'save_preset': 'Save Preset',
        'scaling_close_button': 'Understood, Close Program',
        'scaling_current_setting': 'Current Windows Scaling: {}%',
        'scaling_explanation': 'This program needs Windows scaling at 100% to work properly. Otherwise, aiming '
                               'positions may drift.',
        'scaling_tutorial_content': '1. Right-click on the desktop and choose "Display settings"\n'
                                    '\n'
                                    '2. Or press Windows Key + I, open "Settings" > "System" > "Display"\n'
                                    '\n'
                                    '3. Locate the "Scale and layout" section\n'
                                    '\n'
                                    '4. Set "Change the size of text, apps, and other items" to 100%\n'
                                    '\n'
                                    '5. If you use multiple monitors, ensure each one is set to 100%\n'
                                    '\n'
                                    '6. Restart or sign out and back in after applying the change\n'
                                    '\n'
                                    '7. Relaunch this program once finished to keep aiming accurate\n'
                                    '\n'
                                    'Tips:\n'
                                    '- If 100% feels too small, consider a higher-resolution monitor\n'
                                    '- You may need to adjust window sizes in other apps afterward\n'
                                    '- Correct scaling keeps aiming precise and stable',
        'scaling_tutorial_title': 'How to Fix:',
        'scaling_warning_main_title': 'Windows Scaling Configuration Issue Detected',
        'scaling_warning_title': 'System Configuration Issue',
        'scope_delay': 'Scope Delay (s)',
        'show_boxes': 'Show Player Boxes',
        'show_confidence': 'Show Detection Confidence',
        'show_fov': 'Show FOV',
        'single_target_mode': 'Single Target Mode (Lock on the nearest enemy at a time)',
        'sound_alert_system': 'Sound Alert System',
        'sound_duration': 'Sound Duration (ms)',
        'sound_frequency': 'Sound Frequency (Hz)',
        'sound_interval': 'Sound Interval (ms)',
        'stability_suppression_d': 'Stability Control (D)',
        'status_panel_compute_mode': 'Compute Mode',
        'status_panel_current_model': 'Current Model',
        'status_panel_off': 'OFF',
        'status_panel_on': 'ON',
        'tab_aim_control': 'Aim Control',
        'tab_auto_features': 'Auto Features',
        'tab_basic': 'Basic Settings',
        'tab_display': 'Display Options',
        'tab_keys': 'Key Settings',
        'tab_preset_management': 'Preset Management',
        'tab_program_control': 'Program Control',
        'target_area_settings': 'Target Area Settings',
        'toggle_auto_aim': 'Toggle Auto Aim',
        'toggle_key': 'Toggle Key:',
        'version_info': 'Version 4.0 - Made with Love',
        'vertical_y': 'Vertical (Y-axis)',
        'view_github': 'View GitHub',
        'window_title': 'Bartledoo_h0pZ_iis20160512@gmail.com'},
 'es': {'about': 'Acerca de',
        'about_subtitle': 'Asistente de apuntado con IA de alto rendimiento',
        'about_title': 'Acerca de Bartledoo',
        'aim_key_1': 'Tecla de apuntado 1:',
        'aim_key_2': 'Tecla de apuntado 2:',
        'aim_key_3': 'Tecla de apuntado 3:',
        'aim_part': 'Parte objetivo:',
        'aim_speed_pid': 'Velocidad de apuntado (PID)',
        'auto_aim': 'Apuntado automático',
        'auto_fire_key_1': 'Tecla de disparo automático 1:',
        'auto_fire_key_2': 'Tecla de disparo automático 2:',
        'auto_fire_target': 'Objetivo de disparo automático:',
        'body': 'Cuerpo',
        'body_width_ratio': 'Proporción de ancho del cuerpo (%)',
        'both': 'Ambos',
        'chinese': 'Chino',
        'close': 'Cerrar',
        'compute_mode': 'Modo de cómputo',
        'config_load_failed': 'Error al cargar la configuración',
        'config_loaded': 'Configuración cargada',
        'config_not_found': 'Archivo de configuración no encontrado, usando valores predeterminados',
        'config_save_failed': 'Error al guardar la configuración',
        'config_saved': 'Configuración guardada',
        'confirm_delete': 'Confirmar eliminación',
        'confirm_overwrite': 'Confirmar sobrescritura',
        'cpu': 'CPU',
        'create_preset': 'Crear perfil',
        'delete_preset': 'Eliminar perfil',
        'detect_interval': 'Intervalo de detección (ms)',
        'donate': 'Donar',
        'donate_en': 'Donate',
        'enable_sound_alert': 'Habilitar alerta sonora (cuando apunto al enemigo)',
        'english': 'Inglés',
        'error_correction_i': 'Corrección de error (I)',
        'exit_and_save': 'Salir y guardar',
        'export_preset': 'Exportar perfil',
        'fire_interval': 'Intervalo de disparo (s)',
        'fov_follow_mouse': 'FOV sigue al ratón',
        'fov_size': 'Tamaño del FOV',
        'function_options': 'Opciones de función',
        'general_params': 'Parámetros generales',
        'gpu_directml': 'DirectML (GPU)',
        'head': 'Cabeza',
        'head_height_ratio': 'Proporción de alto de la cabeza (%)',
        'head_width_ratio': 'Proporción de ancho de la cabeza (%)',
        'horizontal_x': 'Horizontal (eje X)',
        'i_am_human': 'Soy humano',
        'import_preset': 'Importar perfil',
        'join_discord': 'Unirse a Discord',
        'keep_detecting': 'Mantener detección (incluso sin tecla de apuntado)',
        'key_listening': '[Escuchando tecla...]',
        'keys_and_auto_fire': 'Teclas y disparo automático',
        'language': 'Idioma',
        'load_preset': 'Cargar perfil',
        'min_confidence': 'Confianza mínima (%)',
        'model': 'Model:',
        'model_settings': 'Model Settings',
        'mouse_move_ddxoft': 'ddxoft',
        'mouse_move_method': 'Método de movimiento del ratón:',
        'no_selection': 'Sin selección',
        'open_preset_folder': 'Abrir carpeta de perfiles',
        'open_preset_manager': 'Abrir gestor de perfiles',
        'parameter_name': 'Nombre del parámetro',
        'preset_config': 'Configuración del perfil',
        'preset_error': 'Error',
        'preset_management_features': 'Funciones de gestión de perfiles',
        'preset_manager': 'Gestor de perfiles',
        'preset_success': 'Éxito',
        'preset_warning': 'Advertencia',
        'program_control': 'Control del programa',
        'reaction_speed_p': 'Velocidad de reacción (P)',
        'refresh_preset': 'Actualizar perfil',
        'rename_preset': 'Renombrar perfil',
        'save_preset': 'Guardar perfil',
        'scaling_close_button': 'Entendido, cerrar programa',
        'scaling_current_setting': 'Escalado actual de Windows: {}%',
        'scaling_explanation': 'This program needs Windows scaling at 100% to work properly. Otherwise, aiming '
                               'positions may drift.',
        'scaling_tutorial_content': '1. Right-click on the desktop and choose "Display settings"\n'
                                    '\n'
                                    '2. Or press Windows Key + I, open "Settings" > "System" > "Display"\n'
                                    '\n'
                                    '3. Locate the "Scale and layout" section\n'
                                    '\n'
                                    '4. Set "Change the size of text, apps, and other items" to 100%\n'
                                    '\n'
                                    '5. If you use multiple monitors, ensure each one is set to 100%\n'
                                    '\n'
                                    '6. Restart or sign out and back in after applying the change\n'
                                    '\n'
                                    '7. Relaunch this program once finished to keep aiming accurate\n'
                                    '\n'
                                    'Tips:\n'
                                    '- If 100% feels too small, consider a higher-resolution monitor\n'
                                    '- You may need to adjust window sizes in other apps afterward\n'
                                    '- Correct scaling keeps aiming precise and stable',
        'scaling_tutorial_title': 'How to Fix:',
        'scaling_warning_main_title': 'Windows Scaling Configuration Issue Detected',
        'scaling_warning_title': 'System Configuration Issue',
        'scope_delay': 'Retardo de mira (s)',
        'show_boxes': 'Mostrar recuadros',
        'show_confidence': 'Mostrar confianza de detección',
        'show_fov': 'Mostrar FOV',
        'single_target_mode': 'Modo objetivo único (bloquea al enemigo más cercano)',
        'sound_alert_system': 'Sistema de alerta sonora',
        'sound_duration': 'Duración del sonido (ms)',
        'sound_frequency': 'Frecuencia de sonido (Hz)',
        'sound_interval': 'Intervalo de sonido (ms)',
        'stability_suppression_d': 'Control de estabilidad (D)',
        'status_panel_compute_mode': 'Modo de cómputo',
        'status_panel_current_model': 'Modelo actual',
        'status_panel_off': 'Apagado',
        'status_panel_on': 'Encendido',
        'tab_aim_control': 'Control de apuntado',
        'tab_auto_features': 'Funciones automáticas',
        'tab_basic': 'Configuración básica',
        'tab_display': 'Opciones de pantalla',
        'tab_keys': 'Configuración de teclas',
        'tab_preset_management': 'Gestión de perfiles',
        'tab_program_control': 'Control del programa',
        'target_area_settings': 'Ajustes del área objetivo',
        'toggle_auto_aim': 'Alternar apuntado automático',
        'toggle_key': 'Tecla de alternancia:',
        'version_info': 'Versión 4.0 - Hecho con cariño',
        'vertical_y': 'Vertical (eje Y)',
        'view_github': 'Ver GitHub',
        'window_title': 'Bartledoo_h0pZ_iis20160512@gmail.com'},
 'fr': {'about': 'À propos',
        'about_subtitle': 'Assistant de visée IA haute performance',
        'about_title': "À propos d'Bartledoo",
        'aim_key_1': 'Touche de visée 1 :',
        'aim_key_2': 'Touche de visée 2 :',
        'aim_key_3': 'Touche de visée 3 :',
        'aim_part': 'Zone visée :',
        'aim_speed_pid': 'Vitesse de visée (PID)',
        'auto_aim': 'Visée automatique',
        'auto_fire_key_1': 'Touche de tir automatique 1 :',
        'auto_fire_key_2': 'Touche de tir automatique 2 :',
        'auto_fire_target': 'Cible du tir automatique :',
        'body': 'Corps',
        'body_width_ratio': 'Ratio de largeur du corps (%)',
        'both': 'Les deux',
        'chinese': 'Chinois',
        'close': 'Fermer',
        'compute_mode': 'Mode de calcul',
        'config_load_failed': 'Échec du chargement de la configuration',
        'config_loaded': 'Configuration chargée',
        'config_not_found': 'Fichier de configuration introuvable, utilisation des valeurs par défaut',
        'config_save_failed': "Échec de l'enregistrement de la configuration",
        'config_saved': 'Configuration enregistrée',
        'confirm_delete': 'Confirmer la suppression',
        'confirm_overwrite': "Confirmer l'écrasement",
        'cpu': 'CPU',
        'create_preset': 'Créer un profil',
        'delete_preset': 'Supprimer le profil',
        'detect_interval': 'Intervalle de détection (ms)',
        'donate': 'Faire un don',
        'donate_en': 'Donate',
        'enable_sound_alert': "Activer l'alerte sonore (lorsqu'un ennemi est visé)",
        'english': 'Anglais',
        'error_correction_i': "Correction d'erreur (I)",
        'exit_and_save': 'Quitter et enregistrer',
        'export_preset': 'Exporter un profil',
        'fire_interval': 'Intervalle de tir (s)',
        'fov_follow_mouse': 'Le FOV suit la souris',
        'fov_size': 'Taille du FOV',
        'function_options': 'Options de fonction',
        'general_params': 'Paramètres généraux',
        'gpu_directml': 'DirectML (GPU)',
        'head': 'Tête',
        'head_height_ratio': 'Ratio de hauteur de la tête (%)',
        'head_width_ratio': 'Ratio de largeur de la tête (%)',
        'horizontal_x': 'Horizontal (axe X)',
        'i_am_human': 'Je suis humain',
        'import_preset': 'Importer un profil',
        'join_discord': 'Rejoindre Discord',
        'keep_detecting': 'Maintenir la détection (même sans touche de visée)',
        'key_listening': '[En écoute de touche...]',
        'keys_and_auto_fire': 'Touches et tir automatique',
        'language': 'Langue',
        'load_preset': 'Charger le profil',
        'min_confidence': 'Confiance minimale (%)',
        'model': 'Model:',
        'model_settings': 'Model Settings',
        'mouse_move_ddxoft': 'ddxoft',
        'mouse_move_method': 'Méthode de déplacement de la souris :',
        'no_selection': 'Aucune sélection',
        'open_preset_folder': 'Ouvrir le dossier des profils',
        'open_preset_manager': 'Ouvrir le gestionnaire de profils',
        'parameter_name': 'Nom du paramètre',
        'preset_config': 'Configuration du profil',
        'preset_error': 'Erreur',
        'preset_management_features': 'Fonctions de gestion des profils',
        'preset_manager': 'Gestionnaire de profils',
        'preset_success': 'Succès',
        'preset_warning': 'Avertissement',
        'program_control': 'Contrôle du programme',
        'reaction_speed_p': 'Vitesse de réaction (P)',
        'refresh_preset': 'Actualiser le profil',
        'rename_preset': 'Renommer le profil',
        'save_preset': 'Enregistrer le profil',
        'scaling_close_button': 'Compris, fermer le programme',
        'scaling_current_setting': 'Échelle Windows actuelle : {}%',
        'scaling_explanation': 'This program needs Windows scaling at 100% to work properly. Otherwise, aiming '
                               'positions may drift.',
        'scaling_tutorial_content': '1. Right-click on the desktop and choose "Display settings"\n'
                                    '\n'
                                    '2. Or press Windows Key + I, open "Settings" > "System" > "Display"\n'
                                    '\n'
                                    '3. Locate the "Scale and layout" section\n'
                                    '\n'
                                    '4. Set "Change the size of text, apps, and other items" to 100%\n'
                                    '\n'
                                    '5. If you use multiple monitors, ensure each one is set to 100%\n'
                                    '\n'
                                    '6. Restart or sign out and back in after applying the change\n'
                                    '\n'
                                    '7. Relaunch this program once finished to keep aiming accurate\n'
                                    '\n'
                                    'Tips:\n'
                                    '- If 100% feels too small, consider a higher-resolution monitor\n'
                                    '- You may need to adjust window sizes in other apps afterward\n'
                                    '- Correct scaling keeps aiming precise and stable',
        'scaling_tutorial_title': 'How to Fix:',
        'scaling_warning_main_title': 'Windows Scaling Configuration Issue Detected',
        'scaling_warning_title': 'System Configuration Issue',
        'scope_delay': 'Délai de visée (s)',
        'show_boxes': 'Afficher les boîtes',
        'show_confidence': 'Afficher la confiance de détection',
        'show_fov': 'Afficher le FOV',
        'single_target_mode': "Mode cible unique (verrouille l'ennemi le plus proche)",
        'sound_alert_system': "Système d'alerte sonore",
        'sound_duration': 'Durée du son (ms)',
        'sound_frequency': 'Fréquence sonore (Hz)',
        'sound_interval': 'Intervalle sonore (ms)',
        'stability_suppression_d': 'Contrôle de stabilité (D)',
        'status_panel_compute_mode': 'Mode de calcul',
        'status_panel_current_model': 'Modèle actuel',
        'status_panel_off': 'Inactif',
        'status_panel_on': 'Actif',
        'tab_aim_control': 'Contrôle de visée',
        'tab_auto_features': 'Fonctions automatiques',
        'tab_basic': 'Paramètres de base',
        'tab_display': "Options d'affichage",
        'tab_keys': 'Paramètres des touches',
        'tab_preset_management': 'Gestion des profils',
        'tab_program_control': 'Contrôle du programme',
        'target_area_settings': 'Réglages de la zone cible',
        'toggle_auto_aim': 'Basculer la visée automatique',
        'toggle_key': 'Touche de bascule :',
        'version_info': 'Version 4.0 - Fait avec amour',
        'vertical_y': 'Vertical (axe Y)',
        'view_github': 'Voir GitHub',
        'window_title': 'Bartledoo_h0pZ_iis20160512@gmail.com'},
 'hi': {'about': 'परिचय',
        'about_subtitle': 'उच्च प्रदर्शन AI निशाना सहायक',
        'about_title': 'Bartledoo के बारे में',
        'aim_key_1': 'निशाना कुंजी 1:',
        'aim_key_2': 'निशाना कुंजी 2:',
        'aim_key_3': 'निशाना कुंजी 3:',
        'aim_part': 'निशाना भाग:',
        'aim_speed_pid': 'निशाना गति (PID)',
        'auto_aim': 'स्वचालित निशाना',
        'auto_fire_key_1': 'ऑटो फायर कुंजी 1:',
        'auto_fire_key_2': 'ऑटो फायर कुंजी 2:',
        'auto_fire_target': 'ऑटो फायर लक्ष्य:',
        'body': 'शरीर',
        'body_width_ratio': 'शरीर की चौड़ाई अनुपात (%)',
        'both': 'दोनों',
        'chinese': 'चीनी',
        'close': 'बंद करें',
        'compute_mode': 'कंप्यूट मोड',
        'config_load_failed': 'कॉन्फ़िगरेशन लोड करने में विफल',
        'config_loaded': 'कॉन्फ़िगरेशन लोड किया गया',
        'config_not_found': 'कॉन्फ़िगरेशन फ़ाइल नहीं मिली, डिफ़ॉल्ट उपयोग हो रहा है',
        'config_save_failed': 'कॉन्फ़िगरेशन सहेजने में विफल',
        'config_saved': 'कॉन्फ़िगरेशन सहेजा गया',
        'confirm_delete': 'हटाने की पुष्टि करें',
        'confirm_overwrite': 'ओवरराइट की पुष्टि करें',
        'cpu': 'CPU',
        'create_preset': 'प्रीसेट बनाएं',
        'delete_preset': 'प्रीसेट हटाएँ',
        'detect_interval': 'पता लगाने का अंतराल (ms)',
        'donate': 'दान करें',
        'donate_en': 'Donate',
        'enable_sound_alert': 'ध्वनि चेतावनी सक्षम करें (दुश्मन पर निशाना करते समय)',
        'english': 'अंग्रेज़ी',
        'error_correction_i': 'त्रुटि सुधार (I)',
        'exit_and_save': 'बाहर निकलें और सहेजें',
        'export_preset': 'प्रीसेट निर्यात करें',
        'fire_interval': 'फायर अंतराल (s)',
        'fov_follow_mouse': 'FOV माउस का अनुसरण करे',
        'fov_size': 'FOV आकार',
        'function_options': 'फ़ंक्शन विकल्प',
        'general_params': 'सामान्य पैरामीटर',
        'gpu_directml': 'DirectML (GPU)',
        'head': 'सिर',
        'head_height_ratio': 'सिर की ऊँचाई अनुपात (%)',
        'head_width_ratio': 'सिर की चौड़ाई अनुपात (%)',
        'horizontal_x': 'क्षैतिज (X-अक्ष)',
        'i_am_human': 'मैं इंसान हूँ',
        'import_preset': 'प्रीसेट आयात करें',
        'join_discord': 'Discord से जुड़ें',
        'keep_detecting': 'निशाना कुंजी के बिना भी पता लगाना जारी रखें',
        'key_listening': '[कुंजी सुन रहे हैं...]',
        'keys_and_auto_fire': 'कुंजियाँ और ऑटो फायर',
        'language': 'भाषा',
        'load_preset': 'प्रीसेट लोड करें',
        'min_confidence': 'न्यूनतम विश्वसनीयता (%)',
        'model': 'Model:',
        'model_settings': 'Model Settings',
        'mouse_move_ddxoft': 'ddxoft',
        'mouse_move_method': 'माउस मूव विधि:',
        'no_selection': 'कोई चयन नहीं',
        'open_preset_folder': 'प्रीसेट फ़ोल्डर खोलें',
        'open_preset_manager': 'प्रीसेट प्रबंधक खोलें',
        'parameter_name': 'पैरामीटर नाम',
        'preset_config': 'प्रीसेट कॉन्फ़िगरेशन',
        'preset_error': 'त्रुटि',
        'preset_management_features': 'प्रीसेट प्रबंधन सुविधाएँ',
        'preset_manager': 'प्रीसेट प्रबंधक',
        'preset_success': 'सफलता',
        'preset_warning': 'चेतावनी',
        'program_control': 'प्रोग्राम नियंत्रण',
        'reaction_speed_p': 'प्रतिक्रिया गति (P)',
        'refresh_preset': 'प्रीसेट रीफ़्रेश करें',
        'rename_preset': 'प्रीसेट का नाम बदलें',
        'save_preset': 'प्रीसेट सहेजें',
        'scaling_close_button': 'समझा, प्रोग्राम बंद करें',
        'scaling_current_setting': 'वर्तमान Windows स्केलिंग: {}%',
        'scaling_explanation': 'This program needs Windows scaling at 100% to work properly. Otherwise, aiming '
                               'positions may drift.',
        'scaling_tutorial_content': '1. Right-click on the desktop and choose "Display settings"\n'
                                    '\n'
                                    '2. Or press Windows Key + I, open "Settings" > "System" > "Display"\n'
                                    '\n'
                                    '3. Locate the "Scale and layout" section\n'
                                    '\n'
                                    '4. Set "Change the size of text, apps, and other items" to 100%\n'
                                    '\n'
                                    '5. If you use multiple monitors, ensure each one is set to 100%\n'
                                    '\n'
                                    '6. Restart or sign out and back in after applying the change\n'
                                    '\n'
                                    '7. Relaunch this program once finished to keep aiming accurate\n'
                                    '\n'
                                    'Tips:\n'
                                    '- If 100% feels too small, consider a higher-resolution monitor\n'
                                    '- You may need to adjust window sizes in other apps afterward\n'
                                    '- Correct scaling keeps aiming precise and stable',
        'scaling_tutorial_title': 'How to Fix:',
        'scaling_warning_main_title': 'Windows Scaling Configuration Issue Detected',
        'scaling_warning_title': 'System Configuration Issue',
        'scope_delay': 'स्कोप विलंब (s)',
        'show_boxes': 'बॉक्स दिखाएँ',
        'show_confidence': 'डिटेक्शन विश्वसनीयता दिखाएँ',
        'show_fov': 'FOV दिखाएँ',
        'single_target_mode': 'एकल लक्ष्य मोड (निकटतम दुश्मन को लॉक करें)',
        'sound_alert_system': 'ध्वनि चेतावनी प्रणाली',
        'sound_duration': 'ध्वनि अवधि (ms)',
        'sound_frequency': 'ध्वनि आवृत्ति (Hz)',
        'sound_interval': 'ध्वनि अंतराल (ms)',
        'stability_suppression_d': 'स्थिरता नियंत्रण (D)',
        'status_panel_compute_mode': 'कंप्यूट मोड',
        'status_panel_current_model': 'वर्तमान मॉडल',
        'status_panel_off': 'बंद',
        'status_panel_on': 'चालू',
        'tab_aim_control': 'निशाना नियंत्रण',
        'tab_auto_features': 'स्वचालित सुविधाएँ',
        'tab_basic': 'मूल सेटिंग',
        'tab_display': 'डिस्प्ले विकल्प',
        'tab_keys': 'कुंजी सेटिंग',
        'tab_preset_management': 'प्रीसेट प्रबंधन',
        'tab_program_control': 'प्रोग्राम नियंत्रण',
        'target_area_settings': 'लक्ष्य क्षेत्र सेटिंग्स',
        'toggle_auto_aim': 'स्वचालित निशाना टॉगल',
        'toggle_key': 'टॉगल कुंजी:',
        'version_info': 'संस्करण 4.0 - प्यार से बनाया गया',
        'vertical_y': 'ऊर्ध्वाधर (Y-अक्ष)',
        'view_github': 'GitHub देखें',
        'window_title': 'Bartledoo_h0pZ_iis20160512@gmail.com'},
 'ja': {'about': '概要',
        'about_subtitle': '高性能AIエイムアシスタント',
        'about_title': 'Bartledoo について',
        'aim_key_1': 'エイムキー 1:',
        'aim_key_2': 'エイムキー 2:',
        'aim_key_3': 'エイムキー 3:',
        'aim_part': '狙う部位:',
        'aim_speed_pid': 'エイム速度 (PID)',
        'auto_aim': '自動エイム',
        'auto_fire_key_1': '自動射撃キー 1:',
        'auto_fire_key_2': '自動射撃キー 2:',
        'auto_fire_target': '自動射撃の対象:',
        'body': '胴体',
        'body_width_ratio': '胴体幅の比率 (%)',
        'both': '両方',
        'chinese': '中国語',
        'close': '閉じる',
        'compute_mode': '計算モード',
        'config_load_failed': '設定の読み込みに失敗しました',
        'config_loaded': '設定を読み込みました',
        'config_not_found': '設定ファイルが見つかりません。既定値を使用します',
        'config_save_failed': '設定の保存に失敗しました',
        'config_saved': '設定を保存しました',
        'confirm_delete': '削除を確認',
        'confirm_overwrite': '上書きを確認',
        'cpu': 'CPU',
        'create_preset': 'プリセットを作成',
        'delete_preset': 'プリセット削除',
        'detect_interval': '検出間隔 (ms)',
        'donate': '寄付する',
        'donate_en': 'Donate',
        'enable_sound_alert': 'サウンドアラートを有効化 (敵を狙うとき)',
        'english': '英語',
        'error_correction_i': '誤差補正 (I)',
        'exit_and_save': '終了して保存',
        'export_preset': 'プリセットを書き出す',
        'fire_interval': '射撃間隔 (s)',
        'fov_follow_mouse': 'FOVをマウスに追従',
        'fov_size': 'FOVサイズ',
        'function_options': '機能オプション',
        'general_params': '一般パラメータ',
        'gpu_directml': 'DirectML (GPU)',
        'head': '頭',
        'head_height_ratio': '頭部高さの比率 (%)',
        'head_width_ratio': '頭部幅の比率 (%)',
        'horizontal_x': '水平 (X軸)',
        'i_am_human': '私は人間です',
        'import_preset': 'プリセットをインポート',
        'join_discord': 'Discordに参加',
        'keep_detecting': 'エイムキーがなくても検出を維持',
        'key_listening': '[キー待機中...]',
        'keys_and_auto_fire': 'キーと自動射撃',
        'language': '言語',
        'load_preset': 'プリセットを読み込み',
        'min_confidence': '最小信頼度 (%)',
        'model': 'Model:',
        'model_settings': 'Model Settings',
        'mouse_move_ddxoft': 'ddxoft',
        'mouse_move_method': 'マウス移動方法:',
        'no_selection': '選択なし',
        'open_preset_folder': 'プリセットフォルダーを開く',
        'open_preset_manager': 'プリセットマネージャーを開く',
        'parameter_name': 'パラメーター名',
        'preset_config': 'プリセット設定',
        'preset_error': 'エラー',
        'preset_management_features': 'プリセット管理機能',
        'preset_manager': 'プリセットマネージャー',
        'preset_success': '成功',
        'preset_warning': '警告',
        'program_control': 'プログラム制御',
        'reaction_speed_p': '反応速度 (P)',
        'refresh_preset': 'プリセット更新',
        'rename_preset': 'プリセット名を変更',
        'save_preset': 'プリセットを保存',
        'scaling_close_button': '了解、プログラムを閉じる',
        'scaling_current_setting': '現在のWindowsスケーリング: {}%',
        'scaling_explanation': 'This program needs Windows scaling at 100% to work properly. Otherwise, aiming '
                               'positions may drift.',
        'scaling_tutorial_content': '1. Right-click on the desktop and choose "Display settings"\n'
                                    '\n'
                                    '2. Or press Windows Key + I, open "Settings" > "System" > "Display"\n'
                                    '\n'
                                    '3. Locate the "Scale and layout" section\n'
                                    '\n'
                                    '4. Set "Change the size of text, apps, and other items" to 100%\n'
                                    '\n'
                                    '5. If you use multiple monitors, ensure each one is set to 100%\n'
                                    '\n'
                                    '6. Restart or sign out and back in after applying the change\n'
                                    '\n'
                                    '7. Relaunch this program once finished to keep aiming accurate\n'
                                    '\n'
                                    'Tips:\n'
                                    '- If 100% feels too small, consider a higher-resolution monitor\n'
                                    '- You may need to adjust window sizes in other apps afterward\n'
                                    '- Correct scaling keeps aiming precise and stable',
        'scaling_tutorial_title': 'How to Fix:',
        'scaling_warning_main_title': 'Windows Scaling Configuration Issue Detected',
        'scaling_warning_title': 'System Configuration Issue',
        'scope_delay': 'スコープ遅延 (s)',
        'show_boxes': 'ボックスを表示',
        'show_confidence': '検出信頼度を表示',
        'show_fov': 'FOVを表示',
        'single_target_mode': '単一ターゲットモード (最も近い敵をロック)',
        'sound_alert_system': 'サウンドアラートシステム',
        'sound_duration': 'サウンド継続時間 (ms)',
        'sound_frequency': 'サウンド周波数 (Hz)',
        'sound_interval': 'サウンド間隔 (ms)',
        'stability_suppression_d': '安定性制御 (D)',
        'status_panel_compute_mode': '計算モード',
        'status_panel_current_model': '現在のモデル',
        'status_panel_off': 'オフ',
        'status_panel_on': 'オン',
        'tab_aim_control': 'エイム制御',
        'tab_auto_features': '自動機能',
        'tab_basic': '基本設定',
        'tab_display': '表示オプション',
        'tab_keys': 'キー設定',
        'tab_preset_management': 'プリセット管理',
        'tab_program_control': 'プログラム制御',
        'target_area_settings': 'ターゲット領域設定',
        'toggle_auto_aim': '自動エイム切り替え',
        'toggle_key': '切り替えキー:',
        'version_info': 'バージョン 4.0 - 愛を込めて',
        'vertical_y': '垂直 (Y軸)',
        'view_github': 'GitHubを表示',
        'window_title': 'Bartledoo_h0pZ_iis20160512@gmail.com'},
 'ko': {'about': '정보',
        'about_subtitle': '고성능 AI 조준 보조 도구',
        'about_title': 'Bartledoo 정보',
        'aim_key_1': '조준 키 1:',
        'aim_key_2': '조준 키 2:',
        'aim_key_3': '조준 키 3:',
        'aim_part': '조준 부위:',
        'aim_speed_pid': '조준 속도 (PID)',
        'auto_aim': '자동 조준',
        'auto_fire_key_1': '자동 사격 키 1:',
        'auto_fire_key_2': '자동 사격 키 2:',
        'auto_fire_target': '자동 사격 대상:',
        'body': '몸통',
        'body_width_ratio': '몸통 너비 비율 (%)',
        'both': '둘 다',
        'chinese': '중국어',
        'close': '닫기',
        'compute_mode': '연산 모드',
        'config_load_failed': '설정을 불러오지 못했습니다',
        'config_loaded': '설정이 불러와졌습니다',
        'config_not_found': '설정 파일을 찾을 수 없습니다. 기본값 사용',
        'config_save_failed': '설정을 저장하지 못했습니다',
        'config_saved': '설정이 저장되었습니다',
        'confirm_delete': '삭제 확인',
        'confirm_overwrite': '덮어쓰기 확인',
        'cpu': 'CPU',
        'create_preset': '프리셋 생성',
        'delete_preset': '프리셋 삭제',
        'detect_interval': '탐지 간격 (ms)',
        'donate': '기부',
        'donate_en': 'Donate',
        'enable_sound_alert': '사운드 알림 활성화 (적 조준 시)',
        'english': '영어',
        'error_correction_i': '오차 보정 (I)',
        'exit_and_save': '종료 및 저장',
        'export_preset': '프리셋 내보내기',
        'fire_interval': '사격 간격 (s)',
        'fov_follow_mouse': 'FOV 마우스 추적',
        'fov_size': 'FOV 크기',
        'function_options': '기능 옵션',
        'general_params': '일반 매개변수',
        'gpu_directml': 'DirectML (GPU)',
        'head': '머리',
        'head_height_ratio': '머리 높이 비율 (%)',
        'head_width_ratio': '머리 너비 비율 (%)',
        'horizontal_x': '수평 (X축)',
        'i_am_human': '나는 사람입니다',
        'import_preset': '프리셋 가져오기',
        'join_discord': 'Discord 참여',
        'keep_detecting': '조준 키 없이도 탐지 유지',
        'key_listening': '[키 대기 중...]',
        'keys_and_auto_fire': '키 및 자동 사격',
        'language': '언어',
        'load_preset': '프리셋 불러오기',
        'min_confidence': '최소 신뢰도 (%)',
        'model': 'Model:',
        'model_settings': 'Model Settings',
        'mouse_move_ddxoft': 'ddxoft',
        'mouse_move_method': '마우스 이동 방식:',
        'no_selection': '선택 없음',
        'open_preset_folder': '프리셋 폴더 열기',
        'open_preset_manager': '프리셋 관리자 열기',
        'parameter_name': '매개변수 이름',
        'preset_config': '프리셋 구성',
        'preset_error': '오류',
        'preset_management_features': '프리셋 관리 기능',
        'preset_manager': '프리셋 관리자',
        'preset_success': '성공',
        'preset_warning': '경고',
        'program_control': '프로그램 제어',
        'reaction_speed_p': '반응 속도 (P)',
        'refresh_preset': '프리셋 새로 고침',
        'rename_preset': '프리셋 이름 변경',
        'save_preset': '프리셋 저장',
        'scaling_close_button': '이해했습니다, 프로그램 종료',
        'scaling_current_setting': '현재 Windows 스케일링: {}%',
        'scaling_explanation': 'This program needs Windows scaling at 100% to work properly. Otherwise, aiming '
                               'positions may drift.',
        'scaling_tutorial_content': '1. Right-click on the desktop and choose "Display settings"\n'
                                    '\n'
                                    '2. Or press Windows Key + I, open "Settings" > "System" > "Display"\n'
                                    '\n'
                                    '3. Locate the "Scale and layout" section\n'
                                    '\n'
                                    '4. Set "Change the size of text, apps, and other items" to 100%\n'
                                    '\n'
                                    '5. If you use multiple monitors, ensure each one is set to 100%\n'
                                    '\n'
                                    '6. Restart or sign out and back in after applying the change\n'
                                    '\n'
                                    '7. Relaunch this program once finished to keep aiming accurate\n'
                                    '\n'
                                    'Tips:\n'
                                    '- If 100% feels too small, consider a higher-resolution monitor\n'
                                    '- You may need to adjust window sizes in other apps afterward\n'
                                    '- Correct scaling keeps aiming precise and stable',
        'scaling_tutorial_title': 'How to Fix:',
        'scaling_warning_main_title': 'Windows Scaling Configuration Issue Detected',
        'scaling_warning_title': 'System Configuration Issue',
        'scope_delay': '스코프 지연 (s)',
        'show_boxes': '박스 표시',
        'show_confidence': '탐지 신뢰도 표시',
        'show_fov': 'FOV 표시',
        'single_target_mode': '단일 대상 모드 (가장 가까운 적을 한 번에 고정)',
        'sound_alert_system': '사운드 알림 시스템',
        'sound_duration': '사운드 지속 시간 (ms)',
        'sound_frequency': '사운드 주파수 (Hz)',
        'sound_interval': '사운드 간격 (ms)',
        'stability_suppression_d': '안정성 제어 (D)',
        'status_panel_compute_mode': '연산 모드',
        'status_panel_current_model': '현재 모델',
        'status_panel_off': '꺼짐',
        'status_panel_on': '켜짐',
        'tab_aim_control': '조준 제어',
        'tab_auto_features': '자동 기능',
        'tab_basic': '기본 설정',
        'tab_display': '표시 옵션',
        'tab_keys': '키 설정',
        'tab_preset_management': '프리셋 관리',
        'tab_program_control': '프로그램 제어',
        'target_area_settings': '타깃 영역 설정',
        'toggle_auto_aim': '자동 조준 토글',
        'toggle_key': '토글 키:',
        'version_info': '버전 4.0 - 사랑으로 제작',
        'vertical_y': '수직 (Y축)',
        'view_github': 'GitHub 보기',
        'window_title': 'Bartledoo_h0pZ_iis20160512@gmail.com'},
 'pt': {'about': 'Sobre',
        'about_subtitle': 'Assistente de mira com IA de alto desempenho',
        'about_title': 'Sobre o Bartledoo',
        'aim_key_1': 'Tecla de mira 1:',
        'aim_key_2': 'Tecla de mira 2:',
        'aim_key_3': 'Tecla de mira 3:',
        'aim_part': 'Parte mirada:',
        'aim_speed_pid': 'Velocidade de mira (PID)',
        'auto_aim': 'Mira automática',
        'auto_fire_key_1': 'Tecla de disparo automático 1:',
        'auto_fire_key_2': 'Tecla de disparo automático 2:',
        'auto_fire_target': 'Alvo do disparo automático:',
        'body': 'Corpo',
        'body_width_ratio': 'Proporção da largura do corpo (%)',
        'both': 'Ambos',
        'chinese': 'Chinês',
        'close': 'Fechar',
        'compute_mode': 'Modo de processamento',
        'config_load_failed': 'Falha ao carregar configuração',
        'config_loaded': 'Configuração carregada',
        'config_not_found': 'Arquivo de configuração não encontrado; usando padrão',
        'config_save_failed': 'Falha ao salvar configuração',
        'config_saved': 'Configuração salva',
        'confirm_delete': 'Confirmar exclusão',
        'confirm_overwrite': 'Confirmar substituição',
        'cpu': 'CPU',
        'create_preset': 'Criar preset',
        'delete_preset': 'Excluir preset',
        'detect_interval': 'Intervalo de detecção (ms)',
        'donate': 'Doar',
        'donate_en': 'Donate',
        'enable_sound_alert': 'Ativar alerta sonoro (ao mirar no inimigo)',
        'english': 'Inglês',
        'error_correction_i': 'Correção de erro (I)',
        'exit_and_save': 'Sair e salvar',
        'export_preset': 'Exportar preset',
        'fire_interval': 'Intervalo de disparo (s)',
        'fov_follow_mouse': 'FOV segue o mouse',
        'fov_size': 'Tamanho do FOV',
        'function_options': 'Opções de função',
        'general_params': 'Parâmetros gerais',
        'gpu_directml': 'DirectML (GPU)',
        'head': 'Cabeça',
        'head_height_ratio': 'Proporção da altura da cabeça (%)',
        'head_width_ratio': 'Proporção da largura da cabeça (%)',
        'horizontal_x': 'Horizontal (eixo X)',
        'i_am_human': 'Sou humano',
        'import_preset': 'Importar preset',
        'join_discord': 'Entrar no Discord',
        'keep_detecting': 'Manter detecção (mesmo sem tecla de mira)',
        'key_listening': '[Escutando tecla...]',
        'keys_and_auto_fire': 'Teclas e disparo automático',
        'language': 'Idioma',
        'load_preset': 'Carregar preset',
        'min_confidence': 'Confiança mínima (%)',
        'model': 'Model:',
        'model_settings': 'Model Settings',
        'mouse_move_ddxoft': 'ddxoft',
        'mouse_move_method': 'Método de movimento do mouse:',
        'no_selection': 'Nenhuma seleção',
        'open_preset_folder': 'Abrir pasta de presets',
        'open_preset_manager': 'Abrir gerenciador de presets',
        'parameter_name': 'Nome do parâmetro',
        'preset_config': 'Configuração do preset',
        'preset_error': 'Erro',
        'preset_management_features': 'Recursos de gerenciamento de presets',
        'preset_manager': 'Gerenciador de presets',
        'preset_success': 'Sucesso',
        'preset_warning': 'Aviso',
        'program_control': 'Controle do programa',
        'reaction_speed_p': 'Velocidade de reação (P)',
        'refresh_preset': 'Atualizar preset',
        'rename_preset': 'Renomear preset',
        'save_preset': 'Salvar preset',
        'scaling_close_button': 'Entendido, fechar programa',
        'scaling_current_setting': 'Escala atual do Windows: {}%',
        'scaling_explanation': 'This program needs Windows scaling at 100% to work properly. Otherwise, aiming '
                               'positions may drift.',
        'scaling_tutorial_content': '1. Right-click on the desktop and choose "Display settings"\n'
                                    '\n'
                                    '2. Or press Windows Key + I, open "Settings" > "System" > "Display"\n'
                                    '\n'
                                    '3. Locate the "Scale and layout" section\n'
                                    '\n'
                                    '4. Set "Change the size of text, apps, and other items" to 100%\n'
                                    '\n'
                                    '5. If you use multiple monitors, ensure each one is set to 100%\n'
                                    '\n'
                                    '6. Restart or sign out and back in after applying the change\n'
                                    '\n'
                                    '7. Relaunch this program once finished to keep aiming accurate\n'
                                    '\n'
                                    'Tips:\n'
                                    '- If 100% feels too small, consider a higher-resolution monitor\n'
                                    '- You may need to adjust window sizes in other apps afterward\n'
                                    '- Correct scaling keeps aiming precise and stable',
        'scaling_tutorial_title': 'How to Fix:',
        'scaling_warning_main_title': 'Windows Scaling Configuration Issue Detected',
        'scaling_warning_title': 'System Configuration Issue',
        'scope_delay': 'Atraso da mira (s)',
        'show_boxes': 'Mostrar caixas',
        'show_confidence': 'Mostrar confiança da detecção',
        'show_fov': 'Mostrar FOV',
        'single_target_mode': 'Modo alvo único (fixa no inimigo mais próximo)',
        'sound_alert_system': 'Sistema de alerta sonoro',
        'sound_duration': 'Duração do som (ms)',
        'sound_frequency': 'Frequência do som (Hz)',
        'sound_interval': 'Intervalo do som (ms)',
        'stability_suppression_d': 'Controle de estabilidade (D)',
        'status_panel_compute_mode': 'Modo de processamento',
        'status_panel_current_model': 'Modelo atual',
        'status_panel_off': 'Desligado',
        'status_panel_on': 'Ligado',
        'tab_aim_control': 'Controle de mira',
        'tab_auto_features': 'Recursos automáticos',
        'tab_basic': 'Configurações básicas',
        'tab_display': 'Opções de exibição',
        'tab_keys': 'Configurações de teclas',
        'tab_preset_management': 'Gerenciamento de presets',
        'tab_program_control': 'Controle do programa',
        'target_area_settings': 'Configurações da área alvo',
        'toggle_auto_aim': 'Alternar mira automática',
        'toggle_key': 'Tecla de alternância:',
        'version_info': 'Versão 4.0 - Feito com carinho',
        'vertical_y': 'Vertical (eixo Y)',
        'view_github': 'Ver GitHub',
        'window_title': 'Bartledoo_h0pZ_iis20160512@gmail.com'},
 'ru': {'about': 'О программе',
        'about_subtitle': 'Высокопроизводительный AI-помощник прицеливания',
        'about_title': 'Об Bartledoo',
        'aim_key_1': 'Клавиша прицела 1:',
        'aim_key_2': 'Клавиша прицела 2:',
        'aim_key_3': 'Клавиша прицела 3:',
        'aim_part': 'Зона прицеливания:',
        'aim_speed_pid': 'Скорость прицеливания (PID)',
        'auto_aim': 'Автоприцел',
        'auto_fire_key_1': 'Клавиша автоогня 1:',
        'auto_fire_key_2': 'Клавиша автоогня 2:',
        'auto_fire_target': 'Цель автоогня:',
        'body': 'Тело',
        'body_width_ratio': 'Ширина тела (%)',
        'both': 'Оба',
        'chinese': 'Китайский',
        'close': 'Закрыть',
        'compute_mode': 'Режим вычисления',
        'config_load_failed': 'Не удалось загрузить конфигурацию',
        'config_loaded': 'Конфигурация загружена',
        'config_not_found': 'Файл конфигурации не найден, используются значения по умолчанию',
        'config_save_failed': 'Не удалось сохранить конфигурацию',
        'config_saved': 'Конфигурация сохранена',
        'confirm_delete': 'Подтвердить удаление',
        'confirm_overwrite': 'Подтвердить перезапись',
        'cpu': 'CPU',
        'create_preset': 'Создать пресет',
        'delete_preset': 'Удалить пресет',
        'detect_interval': 'Интервал обнаружения (мс)',
        'donate': 'Пожертвовать',
        'donate_en': 'Donate',
        'enable_sound_alert': 'Включить звуковое оповещение (при прицеливании во врага)',
        'english': 'Английский',
        'error_correction_i': 'Коррекция ошибки (I)',
        'exit_and_save': 'Выйти и сохранить',
        'export_preset': 'Экспортировать пресет',
        'fire_interval': 'Интервал выстрела (с)',
        'fov_follow_mouse': 'FOV следует за мышью',
        'fov_size': 'Размер FOV',
        'function_options': 'Параметры функций',
        'general_params': 'Общие параметры',
        'gpu_directml': 'DirectML (GPU)',
        'head': 'Голова',
        'head_height_ratio': 'Высота головы (%)',
        'head_width_ratio': 'Ширина головы (%)',
        'horizontal_x': 'Горизонталь (ось X)',
        'i_am_human': 'Я человек',
        'import_preset': 'Импортировать пресет',
        'join_discord': 'Присоединиться к Discord',
        'keep_detecting': 'Продолжать обнаружение (даже без клавиши прицела)',
        'key_listening': '[Ожидание клавиши...]',
        'keys_and_auto_fire': 'Клавиши и автоогонь',
        'language': 'Язык',
        'load_preset': 'Загрузить пресет',
        'min_confidence': 'Минимальная уверенность (%)',
        'model': 'Model:',
        'model_settings': 'Model Settings',
        'mouse_move_ddxoft': 'ddxoft',
        'mouse_move_method': 'Метод перемещения мыши:',
        'no_selection': 'Не выбрано',
        'open_preset_folder': 'Открыть папку пресетов',
        'open_preset_manager': 'Открыть менеджер пресетов',
        'parameter_name': 'Имя параметра',
        'preset_config': 'Настройки пресета',
        'preset_error': 'Ошибка',
        'preset_management_features': 'Возможности управления пресетами',
        'preset_manager': 'Менеджер пресетов',
        'preset_success': 'Успех',
        'preset_warning': 'Предупреждение',
        'program_control': 'Управление программой',
        'reaction_speed_p': 'Скорость реакции (P)',
        'refresh_preset': 'Обновить пресет',
        'rename_preset': 'Переименовать пресет',
        'save_preset': 'Сохранить пресет',
        'scaling_close_button': 'Понятно, закрыть программу',
        'scaling_current_setting': 'Текущее масштабирование Windows: {}%',
        'scaling_explanation': 'This program needs Windows scaling at 100% to work properly. Otherwise, aiming '
                               'positions may drift.',
        'scaling_tutorial_content': '1. Right-click on the desktop and choose "Display settings"\n'
                                    '\n'
                                    '2. Or press Windows Key + I, open "Settings" > "System" > "Display"\n'
                                    '\n'
                                    '3. Locate the "Scale and layout" section\n'
                                    '\n'
                                    '4. Set "Change the size of text, apps, and other items" to 100%\n'
                                    '\n'
                                    '5. If you use multiple monitors, ensure each one is set to 100%\n'
                                    '\n'
                                    '6. Restart or sign out and back in after applying the change\n'
                                    '\n'
                                    '7. Relaunch this program once finished to keep aiming accurate\n'
                                    '\n'
                                    'Tips:\n'
                                    '- If 100% feels too small, consider a higher-resolution monitor\n'
                                    '- You may need to adjust window sizes in other apps afterward\n'
                                    '- Correct scaling keeps aiming precise and stable',
        'scaling_tutorial_title': 'How to Fix:',
        'scaling_warning_main_title': 'Windows Scaling Configuration Issue Detected',
        'scaling_warning_title': 'System Configuration Issue',
        'scope_delay': 'Задержка прицела (с)',
        'show_boxes': 'Показать рамки',
        'show_confidence': 'Показывать уверенность обнаружения',
        'show_fov': 'Показать FOV',
        'single_target_mode': 'Режим одной цели (фиксирует ближайшего врага)',
        'sound_alert_system': 'Система звуковых оповещений',
        'sound_duration': 'Длительность звука (мс)',
        'sound_frequency': 'Частота звука (Гц)',
        'sound_interval': 'Интервал звука (мс)',
        'stability_suppression_d': 'Контроль стабильности (D)',
        'status_panel_compute_mode': 'Режим вычисления',
        'status_panel_current_model': 'Текущая модель',
        'status_panel_off': 'Выкл',
        'status_panel_on': 'Вкл',
        'tab_aim_control': 'Контроль прицеливания',
        'tab_auto_features': 'Автофункции',
        'tab_basic': 'Основные настройки',
        'tab_display': 'Параметры отображения',
        'tab_keys': 'Настройки клавиш',
        'tab_preset_management': 'Управление пресетами',
        'tab_program_control': 'Управление программой',
        'target_area_settings': 'Настройки области цели',
        'toggle_auto_aim': 'Переключить автоприцел',
        'toggle_key': 'Клавиша переключения:',
        'version_info': 'Версия 4.0 — Создано с любовью',
        'vertical_y': 'Вертикаль (ось Y)',
        'view_github': 'Открыть GitHub',
        'window_title': 'Bartledoo_h0pZ_iis20160512@gmail.com'},
 'zh_tw': {'about': '關於',
           'about_subtitle': '高效能 AI 瞄準輔助工具',
           'about_title': '關於 Bartledoo',
           'aim_key_1': '瞄準鍵 1：',
           'aim_key_2': '瞄準鍵 2：',
           'aim_key_3': '瞄準鍵 3：',
           'aim_part': '瞄準部位：',
           'aim_speed_pid': '瞄準速度 (PID)',
           'auto_aim': '自動瞄準',
           'auto_fire_key_1': '自動射擊鍵 1：',
           'auto_fire_key_2': '自動射擊鍵 2：',
           'auto_fire_target': '自動射擊目標：',
           'body': '身體',
           'body_width_ratio': '身體寬度比例 (%)',
           'both': '全部',
           'chinese': '中文',
           'close': '關閉',
           'compute_mode': '運算模式',
           'config_load_failed': '設定載入失敗',
           'config_loaded': '設定已載入',
           'config_not_found': '找不到設定檔，使用預設值',
           'config_save_failed': '設定儲存失敗',
           'config_saved': '設定已儲存',
           'confirm_delete': '確認刪除',
           'confirm_overwrite': '確認覆寫',
           'cpu': 'CPU',
           'create_preset': '建立預設',
           'delete_preset': '刪除預設',
           'detect_interval': '偵測間隔 (ms)',
           'donate': '捐款',
           'donate_en': 'Donate',
           'enable_sound_alert': '啟用音效提醒（瞄準到敵人時）',
           'english': '英文',
           'error_correction_i': '誤差修正 (I)',
           'exit_and_save': '離開並儲存',
           'export_preset': '匯出預設',
           'fire_interval': '射擊間隔 (秒)',
           'fov_follow_mouse': 'FOV 跟隨滑鼠',
           'fov_size': 'FOV 大小',
           'function_options': '功能選項',
           'general_params': '通用參數',
           'gpu_directml': 'DirectML (GPU)',
           'head': '頭部',
           'head_height_ratio': '頭部高度比例 (%)',
           'head_width_ratio': '頭部寬度比例 (%)',
           'horizontal_x': '水平 (X 軸)',
           'i_am_human': '我是人類',
           'import_preset': '匯入預設',
           'join_discord': '加入 Discord',
           'keep_detecting': '保持偵測（即使未按瞄準鍵）',
           'key_listening': '[偵測按鍵中...]',
           'keys_and_auto_fire': '按鍵與自動射擊',
           'language': '語言',
           'load_preset': '載入預設',
           'min_confidence': '最低信心值 (%)',
           'model': 'Model:',
           'model_settings': 'Model Settings',
           'mouse_move_ddxoft': 'ddxoft',
           'mouse_move_method': '滑鼠移動方式：',
           'no_selection': '尚未選取',
           'open_preset_folder': '開啟預設資料夾',
           'open_preset_manager': '開啟預設管理員',
           'parameter_name': '參數名稱',
           'preset_config': '預設設定',
           'preset_error': '錯誤',
           'preset_management_features': '預設管理功能',
           'preset_manager': '預設管理員',
           'preset_success': '成功',
           'preset_warning': '警告',
           'program_control': '程式控制',
           'reaction_speed_p': '反應速度 (P)',
           'refresh_preset': '重新整理預設',
           'rename_preset': '重新命名預設',
           'save_preset': '儲存預設',
           'scaling_close_button': '了解，關閉程式',
           'scaling_current_setting': '目前 Windows 縮放比例：{}%',
           'scaling_explanation': '此程式需要將 Windows 縮放比例設為 100% 才能正常運作。否則瞄準位置可能會偏移。',
           'scaling_tutorial_content': '1. 在桌面按右鍵並選擇「顯示設定」\n'
                                       '\n'
                                       '2. 或按 Windows 鍵 + I，打開「設定」 > 「系統」 > 「顯示」\n'
                                       '\n'
                                       '3. 找到「縮放比例和版面配置」區段\n'
                                       '\n'
                                       '4. 將「變更文字、應用程式和其他項目的顯示大小」設為 100%\n'
                                       '\n'
                                       '5. 如果您使用多個螢幕，請確保每個螢幕都設為 100%\n'
                                       '\n'
                                       '6. 套用變更後重新啟動或登出再登入\n'
                                       '\n'
                                       '7. 完成後重新啟動此程式以保持瞄準準確性\n'
                                       '\n'
                                       '提示：\n'
                                       '- 如果 100% 感覺太小，請考慮使用更高解析度的螢幕\n'
                                       '- 之後您可能需要在其他應用程式中調整視窗大小\n'
                                       '- 正確的縮放比例可保持瞄準精準和穩定',
           'scaling_tutorial_title': '如何修正：',
           'scaling_warning_main_title': '偵測到 Windows 縮放比例設定問題',
           'scaling_warning_title': '系統設定問題',
           'scope_delay': '開鏡延遲 (秒)',
           'show_boxes': '顯示框體',
           'show_confidence': '顯示偵測信心值',
           'show_fov': '顯示 FOV',
           'single_target_mode': '單一目標模式（一次鎖定最近的敵人）',
           'sound_alert_system': '音效提醒系統',
           'sound_duration': '音效持續時間 (ms)',
           'sound_frequency': '音效頻率 (Hz)',
           'sound_interval': '音效間隔 (ms)',
           'stability_suppression_d': '穩定控制 (D)',
           'status_panel_compute_mode': '運算模式',
           'status_panel_current_model': '目前模型',
           'status_panel_off': '停用',
           'status_panel_on': '啟用',
           'tab_aim_control': '瞄準控制',
           'tab_auto_features': '自動功能',
           'tab_basic': '基本設定',
           'tab_display': '顯示選項',
           'tab_keys': '按鍵設定',
           'tab_preset_management': '預設管理',
           'tab_program_control': '程式控制',
           'target_area_settings': '目標區域設定',
           'toggle_auto_aim': '切換自動瞄準',
           'toggle_key': '切換鍵：',
           'version_info': '版本 4.0 - 用心打造',
           'vertical_y': '垂直 (Y 軸)',
           'view_github': '查看 GitHub',
           'window_title': 'Bartledoo_h0pZ_iis20160512@gmail.com'}}
